import './normalize.css'
import './globals.scss'
import { Inter } from 'next/font/google'
import HeaderComponents from "@/coponents/header";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App Yep',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderComponents/>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
